language: ruby

services:
  - postgresql

cache: bundler

before_install:
  - gem install bundler -v 1.17.3
  - gem install bundler -v 2.0.1

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rails spec

notifications:
  email: false
