language: ruby
services:
- postgresql
bundler_args: "--jobs=3 --retry=3"
cache: bundler
before_install:
- gem install bundler -v 1.17.3
- gem install bundler -v 2.0.1
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: dYcLnJriDu17uwQaBduRDwDLhxe/ZN2V2r6gt5JfnS4MAuCeP1Ke2biejmJY3X4zmPoGEWhh5CZ7WyvHzlIz0LvqW77TyPx+2pA2UwitFrYQhIlniWY8kjg4CDXbviTbTLBgO+CmHTH6GxW4YmMayVbyoF7JRtspCgLY8mY9iBMV8VUucVfMGrleO6VbMjWasQgBn56J5YZFBCjliRpCDgICULgvBUqA1GZ+WAs9tOU4szcdCamJQaJfX8Dzano9qBSFAR9sNkeNVdBjDvy86cFn7s+ARtNAxVuqu3RhvVgZVUgANX0zWCuAzv02+VmTwJR4kVTidfJsTJ64w/Wzsc6PZtlvNiJnMeC+UUOPjt/fdVVytDYTpRf8FQL455ZrhXovoNdO1ubx3q62SMWi5QQk65EKwRUwa8ix2ChlGqhqFzwK5ulj6yFSAiq6qHieBCnhuS/1MpMMiL937trM/uLLSLSDYKjueSQqA7KGpkJEJ6iDIvx6INJdRTYfB38z5wnFZcIacJz1w1ykfWCGJpy5dSx9JpdqiDhm1dSU/t2DS1hsvZb4zPp0CBXkHSZqUuYzUKzXUYunoN9wjdn7F7LxlhYFiFw00BQR6zDoaYbBixP614KkXOchIx3F4Ca9DStC37K7fckhHLIw/LijTCuMxW1fYMB++nIjwYFzgtY=
  app: ujull-gnote
  on:
    repo: 256hax/ujull-gnote
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec spec
