language: ruby

services:
  - postgresql

bundler_args: --jobs=3 --retry=3
cache: bundler

before_install:
  # Install latest 1.x and 2.x bundler for Avoid GemNotFoundException error.
  - gem install bundler -v 1.17.3
  - gem install bundler -v 2.0.1

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rake db:setup
  - bundle exec rspec spec

notifications:
  email: false
